feat: add global search for events, experiments and archives.
chaos-mesh/chaos-mesh pull request #1034
Opened 2020-10-12 10:34 UTC by wanyoulc

### What problem does this PR solve?

This PR adds a search trigger button, and a global search modal for searching events, experiments, and archives more conveniently.

### What is changed and how does it work?
-  update /ui/lib/search to add search logic, which use automata to achieve keyword matching
-  add a nested route in EventsTable for linking to appropriate event when a user clicks search item
-  add a component named SearchTrigger, which is a search trigger button on Header
-  add a component named Search, which contains the main part of the search functionality
-  remove global redirect route

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

2020-10-12 10:41 UTC, fewdan commented
@wanyoulc    Please sign off DCO first.

2020-10-14 05:25 UTC, g1eny0ung commented on ui/src/components/EventDetail/index.tsx
> +  const fetchEvent = () => {
@fewdan Seems that we need to create an interface to get individual events.

2020-10-14 05:43 UTC, g1eny0ung requested changes

2020-10-14 05:43 UTC, g1eny0ung commented on ui/src/components/TopContainer/Header.tsx
> +      maxWidth: '35rem',
I think it's better to use the percent to define the width, px for height.

2020-10-14 05:43 UTC, g1eny0ung commented on ui/src/components/TopContainer/Header.tsx
> +const SearchTrigger: React.FC = () => {
Encapsulate this component into a file?

Also, add a global shortcut to trigger searching? like `Ctrl/CMD + P`.

2020-10-14 05:48 UTC, g1eny0ung commented
@wanyoulc And also, the new searching styles don't fit the dark mode. PTAL.

2020-10-21 06:48 UTC, g1eny0ung approved these changes
LGTM

2020-10-26 06:39 UTC, fewdan submitted a review, later dismissed
LGTM

2020-10-26 08:24 UTC, g1eny0ung commented
/merge

2020-10-26 10:49 UTC, fewdan commented
Please resolve the conflict files.  @wanyoulc

2020-10-27 02:33 UTC, g1eny0ung approved these changes

2020-10-27 03:40 UTC, zhouqiang-cl approved these changes
LGTM

2020-10-27 03:40 UTC, merged