support container specified iochaos
chaos-mesh/chaos-mesh pull request #1159
Opened 2020-11-09 03:50 UTC by YangKeao

Signed-off-by: Yang Keao <keao.yang@yahoo.com>

### What problem does this PR solve?

Fix #1156

2020-11-09 03:51 UTC, YangKeao commented
/run-e2e-tests

2020-11-09 03:51 UTC, YangKeao commented
/run-e2e-tests

2020-11-09 05:37 UTC, YangKeao commented
/run-e2e-tests

2020-11-11 03:19 UTC, cwen0 approved these changes
LGTM

2020-11-11 05:53 UTC, STRRL requested changes
rest LGTM

2020-11-11 05:53 UTC, STRRL commented on controllers/podiochaos/types.go
> +		len(strings.TrimSpace(*chaos.Spec.Container)) != 0 {
I have a little confusing about strings.TrimSpace(). I found we use it on several places. Why we need it?

2020-11-11 05:53 UTC, STRRL commented on controllers/podiochaos/types.go
> +				containerID = container.ContainerID
```suggestion
				containerID = container.ContainerID
				break
```

2020-11-11 06:05 UTC, YangKeao commented on controllers/podiochaos/types.go
> +		len(strings.TrimSpace(*chaos.Spec.Container)) != 0 {
#846 brings in these codes. At least, it's better to have than not (not a convincing reason :facepalm: )

2020-11-11 06:06 UTC, YangKeao commented on controllers/podiochaos/types.go
> +				containerID = container.ContainerID
Fixed

2020-11-11 06:06 UTC, YangKeao commented
/run-e2e-tests

2020-11-11 06:10 UTC, STRRL approved these changes
LGTM

2020-11-11 06:11 UTC, STRRL commented on controllers/podiochaos/types.go
> +		len(strings.TrimSpace(*chaos.Spec.Container)) != 0 {
¯\_(ツ)_/¯

2020-11-11 06:51 UTC, fewdan approved these changes
LGTM

2020-11-11 06:51 UTC, merged