Adding helm chart options for psp enabled clusters
chaos-mesh/chaos-mesh pull request #1172
Opened 2020-11-12 13:44 UTC by stekole

Signed-off-by: Stefan Kolesnikowicz <stefan.kolesnikowicz@achievers.com>

### What problem does this PR solve?
Kubernetes clusters with PSP (podsecuritypolicy) enabled will not allow chaos-daemon to start up. 

### What is changed and how does it work?

I added a service account, rbac policy and a pod security policy to the chaos-daemon. This allows more access to the pods on clusters which have pod security policies enabled. 

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ X ] Manual test (add detailed scripts or steps below)
- [ ] No code

Tested with and without podsecurity policies enabled.

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

2020-11-12 13:45 UTC, stekole commented
Sorry for the issues submitting this PR. Its my first time. I think I am sorted.

2020-11-12 14:34 UTC, STRRL commented
Hi @stekole , thanks for your contribution!  😁

Here is a failed github action that blocks this PR. It is caused by consistent validation between `install.sh` and helm files. 

You could follow below steps to fix it:
- execute `./hack/update_install_script.sh`
- `install.sh` will be updated, execute `make check`, it will do these checks locally
- commit changes

2020-11-12 14:51 UTC, stekole commented
@STRRL  - Thanks for the help. I am unsure the failure now. Any recommendations?

2020-11-12 15:08 UTC, STRRL commented
Hi @stekole , here is a annotation like `controller-gen.kubebuilder.io/version: v0.2.4`.
It should be `controller-gen.kubebuilder.io/version: v0.2.5`.

You could re-install `controller-gen` versioned v0.2.5 with `go get sigs.k8s.io/controller-tools/cmd/controller-gen@v0.2.5`; then execute `make check` and commit the changes.

2020-11-12 16:45 UTC, stekole commented
awesome thanks!

2020-11-16 05:36 UTC, YangKeao submitted a review, later dismissed
LGTM

2020-11-16 05:54 UTC, fewdan approved these changes
LGTM

2020-11-16 06:06 UTC, STRRL requested changes
Although this podsecuritypolicy is still a little "over-powerd", it represents enough privilledges what we need.

rest LGTM

2020-11-16 06:06 UTC, STRRL commented on helm/chaos-mesh/templates/chaos-daemon-rbac.yaml
> +  runAsUser:
seems duplicated with lines 91 - 94

2020-11-16 13:57 UTC, stekole commented on helm/chaos-mesh/templates/chaos-daemon-rbac.yaml
> +  runAsUser:
Good eye

2020-11-19 07:50 UTC, STRRL approved these changes
LGTM

2020-11-19 07:55 UTC, YangKeao approved these changes
LGTM

2020-11-19 07:55 UTC, YangKeao commented
/merge

2020-11-19 08:33 UTC, merged