serialize ipset operation with the same name
chaos-mesh/chaos-mesh pull request #1448
Opened 2021-01-25 09:18 UTC by YangKeao

Signed-off-by: Yang Keao <keao.yang@yahoo.com>

The problem is that: ipset is not isolated with network namespace until 3.12. So if multiple `FlushIPSet` requests with the same ipset name for different container arrives the daemon, and executed at the same time, the operation will fail:

```
-> create -> flush -> add -> rename -> return successfully
-> create -> flush ------------------------> add (Fail!)
```

I have though about two different solutions for it:

1. Add a pid to the name of ipset to simulate the isolation
2. Use a lock to serialize the ipset operations

I choose the second solution, because the first one needs more modification, and the pid is not a good identifier for namespace. However, the second choice will bring performance degradation for every users.

2021-01-25 09:23 UTC, YangKeao commented
/run-e2e-tests

2021-01-25 09:28 UTC, YangKeao commented
/run-e2e-tests

2021-01-25 09:52 UTC, YangKeao commented
/run-e2e-tests

2021-01-25 13:53 UTC, YangKeao commented
/run-e2e-tests

2021-01-25 13:56 UTC, YangKeao commented
/run-e2e-tests

2021-01-26 03:07 UTC, STRRL requested changes
rest LGTM 

Actually, I prefer the first solution. I think we could the container id as a part of ipset name.

2021-01-26 05:29 UTC, YangKeao commented on pkg/chaosdaemon/server.go
> +		IPSetLocker:              locker.New(),
Fixed.

2021-01-26 05:30 UTC, YangKeao commented on pkg/chaosdaemon/ipset_server.go
> +		s.IPSetLocker.Unlock(ipset.Name)
Fixed

2021-01-26 05:45 UTC, STRRL approved these changes
LGTM

2021-01-27 07:12 UTC, cwen0 approved these changes
LGTM

2021-01-27 07:12 UTC, cwen0 commented
/merge

2021-01-27 07:30 UTC, merged