cri-o support
chaos-mesh/chaos-mesh pull request #1530
Opened 2021-03-02 11:45 UTC by YangKeao

### What problem does this PR solve?

Fix #1528 

### What is changed and how does it work?

It seems that there doesn't exist an CRI-O official client, and I have to copy the implementation of client from https://github.com/cri-o/cri-o/blob/master/internal/client/client.go . The compatibility of the protocol is not guaranteed, which means the `pid` field may be moved or renamed in the future, but it works fine at least now.

The `ContainerKill` hasn't been implemented yet. Maybe sending a signal manually could be an option. I should read the implementation of `docker kill` and find what it does besides sending signal.

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

I started a minikube virtual machine with cri-o by `minikube start --insecure-registry "192.168.39.0/24" --container-runtime=cri-o`, and then run `helm install chaos-mesh helm/chaos-mesh -n chaos-testing --set chaosDaemon.runtime="crio" --set chaosDaemon.socketPath="/var/run/crio/crio.sock"` to install the Chaos Mesh. In this cluster, I run the e2e test of `Netem`, and it works well :+1: .

2021-03-03 06:16 UTC, YangKeao commented
/run-e2e-tests

2021-03-03 06:44 UTC, YangKeao commented
/run-e2e-tests

2021-03-03 11:03 UTC, STRRL commented
Is there possible that implementing `crClient`s by https://github.com/kubernetes/cri-api?

Reference:
https://github.com/kubernetes-sigs/cri-tools/blob/master/cmd/crictl/main_unix.go
https://github.com/kubernetes-sigs/cri-tools/blob/master/cmd/crictl/util.go#L154

2021-03-03 15:45 UTC, YangKeao commented
> Is there possible that implementing `crClient`s by https://github.com/kubernetes/cri-api?
> 
> Reference:
> https://github.com/kubernetes-sigs/cri-tools/blob/master/cmd/crictl/main_unix.go
> https://github.com/kubernetes-sigs/cri-tools/blob/master/cmd/crictl/util.go#L154

As I know, it doesn't provide pid information.

2021-03-03 16:22 UTC, yeya24 commented
> > Is there possible that implementing `crClient`s by https://github.com/kubernetes/cri-api?
> > Reference:
> > https://github.com/kubernetes-sigs/cri-tools/blob/master/cmd/crictl/main_unix.go
> > https://github.com/kubernetes-sigs/cri-tools/blob/master/cmd/crictl/util.go#L154
> 
> As I know, it doesn't provide pid information.

For CRI-O, the PID is provided via the [ContainerStatusResponse](https://github.com/kubernetes/cri-api/blob/master/pkg/apis/runtime/v1alpha2/api.proto#L979) message if `verbose` is enabled. 
The code is [here](https://github.com/cri-o/cri-o/blob/master/server/container_status.go#L105).

But this behavior is not part of the CRI Spec, so it is possible to change and I am not sure about other Linux-based CRI implementations. 
If this is a common behavior I feel using CRI API would be a better choice.

2021-03-04 03:13 UTC, STRRL commented
I realize that the `PID` thing is not declarer explicitly in CRI. We'd better not use it. 🙈

2021-03-08 05:15 UTC, STRRL requested changes
rest LGTM

2021-03-08 05:15 UTC, STRRL commented on pkg/chaosdaemon/container_test.go
> +
groupimports issues.

2021-03-08 05:15 UTC, STRRL commented on pkg/chaosdaemon/ipset_server_test.go
> +
ditto

2021-03-08 05:15 UTC, STRRL commented on pkg/chaosdaemon/iptables_server_test.go
> +
ditto

2021-03-08 05:15 UTC, STRRL commented on pkg/chaosdaemon/server.go
> +
ditto

2021-03-08 06:14 UTC, YangKeao commented on pkg/chaosdaemon/server.go
> +
Fixed

2021-03-08 06:14 UTC, YangKeao commented on pkg/chaosdaemon/iptables_server_test.go
> +
Fixed

2021-03-08 06:14 UTC, YangKeao commented on pkg/chaosdaemon/ipset_server_test.go
> +
Fixed

2021-03-08 06:14 UTC, YangKeao commented on pkg/chaosdaemon/container_test.go
> +
Fixed

2021-03-08 06:15 UTC, YangKeao commented on pkg/chaosdaemon/server.go
> +
Fixed

2021-03-08 07:08 UTC, STRRL approved these changes
LGTM

2021-03-15 12:05 UTC, cwen0 approved these changes
LGTM

2021-03-15 12:05 UTC, cwen0 commented
/merge

2021-03-15 15:01 UTC, YangKeao commented
/merge

2021-03-15 15:17 UTC, merged

2021-03-15 15:54 UTC, YangKeao commented
/merge