Refactoring Kubernetes recommanded labels labels
chaos-mesh/chaos-mesh pull request #1538
Opened 2021-03-05 08:58 UTC by nlamirault

### What problem does this PR solve?

### What is changed and how does it work?

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

2021-03-05 09:18 UTC, WangXiangUSTC commented
Need to run hack/update_install_script.sh to update install.sh

2021-03-08 05:34 UTC, STRRL commented on helm/chaos-mesh/templates/_helpers.tpl
> +{{ toYaml .Values.customLabels | indent 4 }}
We do not need `indent 4` here

2021-03-08 05:41 UTC, STRRL requested changes
Thanks for your contribution! @nlamirault! :)

rest LGTM!

2021-03-08 05:41 UTC, STRRL commented on helm/chaos-mesh/templates/_helpers.tpl
> +app.kubernetes.io/part-of: {{ template "chaos-mesh.name" . }}
There are some whitespaces at the end of line 37 and line 41, please remove them.

2021-03-08 05:41 UTC, STRRL commented on helm/chaos-mesh/README.md
> +| customLabels | object | `{}` |  |
```suggestion
| `customLabels` | Customized labels that will be tagged on all the resources of Chaos Mesh | `{}` |
```

2021-03-08 05:51 UTC, STRRL commented on helm/chaos-mesh/Chart.yaml
> +version: v0.3.0
How do we maintain this version? It seems to be not updated for a long time. 😰@cwen0

2021-03-08 13:41 UTC, nlamirault commented
@STRRL any idea why it fails ?

2021-03-08 15:35 UTC, STRRL commented
Hi @nlamirault, our integration tests are not stable now, I will keep retrying that.

And you should fix the DCO.

2021-03-15 03:33 UTC, STRRL commented
Hi @nlamirault, it seems you need to execute `hack/update_install_script.sh` again, there are some differences between yaml files and install.sh, it causes CI failed.

2021-03-17 03:15 UTC, STRRL commented
Hi @nlamirault, I found that there are two commits ecfd163, 86197b2 that break the DCO check. I am afraid that we could not merge this PR until the DCO fixed.🥺

2021-04-21 13:36 UTC, nlamirault commented
See #1735

2021-04-21 13:36 UTC, closed without merging