Use v1 rather than v1beta1 for admissionregistration.k8s.io apiVersion in webhooks
chaos-mesh/chaos-mesh pull request #1558
Opened 2021-03-11 17:01 UTC by anuragpaliwal80

### What problem does this PR solve?

As per k8s release `1.16` notes (Refer: https://v1-16.docs.kubernetes.io/docs/setup/release/notes/ ):

The `admissionregistration.k8s.io/v1beta1` versions of `MutatingWebhookConfiguration` and `ValidatingWebhookConfiguration` are deprecated and will no longer be served in v1.19. Use admissionregistration.k8s.io/v1 instead.

### What is changed and how does it work?
There is no change from functionality point of view with new apiVersion.
 
### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

2021-03-12 05:39 UTC, WangXiangUSTC commented
ci failed, get an error when creating chaos experiment:
```
kubectl apply -f network.yaml
Error from server (InternalError): error when creating "../chaos_test/network.yaml": Internal error occurred: failed calling webhook "mnetworkchaos.kb.io": expected response.uid="c6884265-3525-4610-ba94-07ce5e7b04e4", got ""
```
 it seems that the webhook doesn't work, do we need to update the import `k8s.io/api/admission/v1beta1` to `k8s.io/api/admission/v1`, and some other pkg needs to update too, for examples `sigs.k8s.io/controller-runtime/pkg/webhook/admission`

2021-03-12 10:28 UTC, anuragpaliwal80 commented
I am not sure how can I fix the  `Error: api/webhook/inject.go:57:3: cannot use *"github.com/chaos-mesh/chaos-mesh/pkg/webhook/inject".Inject(&req.AdmissionRequest, v.client, v.Config, v.ControllerCfg, v.Metrics) (type "k8s.io/api/admission/v1".AdmissionResponse) as type v1beta1.AdmissionResponse in field value`

Some pointers will be helpful. 

One more thing how can I check this locally?

2021-03-12 11:20 UTC, anuragpaliwal80 commented
FYI.. after setting up my local env, I tried `make` and was able to see this issue locally as well.

2021-03-12 12:13 UTC, anuragpaliwal80 commented
FYI... Tried updating to `sigs.k8s.io/controller-runtime v0.5.14` but same error and tried even the latest one i.e. `0.8.3` and it does not have `sigs.k8s.io/controller-runtime/pkg/runtime/log` which is required for `DNSChaos`

2021-03-12 15:09 UTC, anuragpaliwal80 commented
As per https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.6.5 `runtime/log` has been deprecated.

2021-03-15 03:06 UTC, STRRL commented
Hi @anuragpaliwal80, thanks for your contribution! 😁

I see that you update the imports in `pkg/webhook/inject` from `k8s.io/api/admission/v1beta1` to `k8s.io/api/admission/v1`. I am afraid that change might affect too many things that we'd better split into another PR.

Could we only update the apiVersion of `MutatingWebhookConfiguration` and `ValidatingWebhookConfiguration` in this PR, and upgrade `controller-runtime` in another one?

2021-03-15 04:29 UTC, anuragpaliwal80 commented
Earlier I updated only `apiVersion` in webhooks as https://github.com/chaos-mesh/chaos-mesh/pull/1558/commits/7ac1db0b7ad0ea82bd5aaf111d1feb6883094205 but the build started failing. It looked like the `controller-runtime` we are using i.e. `0.4.0` does not having support of `v1` so I tried updating the `controller-runtime` and then found that we are using `sigs.k8s.io/controller-runtime/pkg/runtime/log` which has been deprecated as mentioned above.
So some chaos mesh expert first needs to remove this deprecated feature as mentioned above.
Once that's done, we will be able to take this PR fwd till then it's sort of block.

2021-03-16 03:05 UTC, STRRL commented
/run-e2e-tests

2021-03-29 12:50 UTC, cwen0 commented
@anuragpaliwal80 CI failed, Can you fix it?

2021-03-30 04:21 UTC, anuragpaliwal80 commented
CI logs is showing error like 
```Error from server (InternalError): error when creating "./delay_chaos.yaml": Internal error occurred: failed calling webhook "mnetworkchaos.kb.io": expected response.uid="ba380f1d-1419-4eda-aed3-05c7516bad65", got ""
```
And I have even tried on k8s version 1.19.4 on my k8s cluster by changing the version to `v1` and it was throwing similar error. So it looks like some other packages needs to be updated to make this work (as mentioned above).

2021-04-06 09:50 UTC, STRRL commented
Hi @anuragpaliwal80, the previous issue might caused by localstack and we have fixed it.

Now tests failed with yaml of webhooks, PTAL, thanks!

2021-04-06 10:59 UTC, anuragpaliwal80 commented
The integration tests are still failing as:
```
Error from server (InternalError): error when creating "./delay_chaos.yaml": Internal error occurred: failed calling webhook "mnetworkchaos.kb.io": expected response.uid="185cb522-1434-482c-8b84-39582b2da374", got ""
```

2021-08-02 10:14 UTC, STRRL commented
very sorry for the late response :sob: 

I think the upgrading of `controller-runtime` had stuck this PR for a long time. I think we could upgrade the `controller-runtime` to the latest version. I am going to work on that right now!

2021-08-03 04:47 UTC, anuragpaliwal80 commented
Thanks for the update. Let me know once you are done with update, I will retry this PR.

2021-08-25 12:37 UTC, STRRL commented
hi @anuragpaliwal80 , as #2193 has been merged, I think you could continue the works on this PR. :P

2021-09-03 02:59 UTC, STRRL commented
> @STRRL Looks like it's working fine. Can you please check why these two checks are still pending?

Hi @anuragpaliwal80 , sorry for the late response. "chaos-mesh/e2e-test" should be triggered manually and "tide" will be triggered automatically when this PR going to be merged, so do not worry about them.

And I think we could remove the compatibility for `admissionregistration.k8s.io/v1beta1`, because the minimum supported kubernetes version is 1.15.

How do you think about it? @YangKeao @cwen0

2021-09-06 11:19 UTC, STRRL commented
> > @STRRL Looks like it's working fine. Can you please check why these two checks are still pending?
> 
> Hi @anuragpaliwal80 , sorry for the late response. "chaos-mesh/e2e-test" should be triggered manually and "tide" will be triggered automatically when this PR going to be merged, so do not worry about them.
> 
> And I think we could remove the compatibility for `admissionregistration.k8s.io/v1beta1`, because the minimum supported kubernetes version is 1.15.
> 
> How do you think about it? @YangKeao @cwen0

I think we'd better do that in other PR, it breaks the forward compatibility.

2021-09-06 11:19 UTC, STRRL approved these changes
LGTM!

2021-09-06 11:19 UTC, STRRL commented
PTAL

/cc @YangKeao

2021-09-08 03:03 UTC, fewdan approved these changes
LGTM

2021-09-08 03:09 UTC, STRRL commented
/merge

2021-09-08 04:34 UTC, STRRL commented
/merge cancel

2021-09-08 04:35 UTC, STRRL requested changes

2021-09-08 04:35 UTC, STRRL commented on helm/chaos-mesh/templates/secrets-configuration.yaml
> +    timeoutSeconds: {{ $timeoutSeconds }}
```suggestion
    {{- if $supportTimeoutSeconds }}
    timeoutSeconds: {{ $timeoutSeconds }}
    {{- end }}
```

2021-09-08 04:35 UTC, STRRL commented on helm/chaos-mesh/templates/secrets-configuration.yaml
> +    timeoutSeconds: {{ $timeoutSeconds }}
sorry for my carelessness, should check `supportTimeoutSeconds` before using `timeoutSeconds`

2021-09-08 12:47 UTC, anuragpaliwal80 commented
@STRRL To update install.sh, I use to execute `./hack/update_install_script.sh` but looks like this script is updated /hack/install.sh and not the install.sh present on main folder.
What should I do to update main install.sh file ?

2021-09-09 10:05 UTC, STRRL commented
> @STRRL To update install.sh, I use to execute `./hack/update_install_script.sh` but looks like this script is updating `/hack/install.sh` and not the main `install.sh` present on main folder.
> What should I do to update main `install.sh` file ?

A little wired. I checkout both your branch and `master` branch, `./hack/update_isntall_script.sh` works well. Could you tell me more detail? :D

2021-09-09 10:24 UTC, anuragpaliwal80 commented
```
Anurags-MacBook-Pro:chaos-mesh apaliwal$ ./hack/update_install_script.sh 
Anurags-MacBook-Pro:chaos-mesh apaliwal$ git st
On branch apaliwal_apiversion_in_webhook
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   helm/chaos-mesh/templates/secrets-configuration.yaml

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	hack/install.sh

no changes added to commit (use "git add" and/or "git commit -a")
Anurags-MacBook-Pro:chaos-mesh apaliwal$ 
```
This is what I am seeing when executing `./hack/update_install_script.sh`. It's not updating the main `install.sh` and there was nothing in `hack/install.sh` as well:
```
Anurags-MacBook-Pro:chaos-mesh apaliwal$ cat hack/install.sh 
---
apiVersion: v1
kind: Namespace
metadata:
  name: chaos-testing
```

2021-09-09 10:32 UTC, anuragpaliwal80 commented
I just notice that there is no install.sh in hack in git repo so I deleted this file locally. (Looks like gets created by me, my bad).
Now after deleting the file `hack\install.sh`, I tried executing the `./hack/update_install_script.sh` but it's not updating `install.sh`. :(

2021-09-10 02:37 UTC, STRRL commented
It seems `timeoutSeconds` indeed will not be updated in the `install.sh`. You could find these `timeoutSeconds` exist in other parts of `1install.sh`. I think it's OK.

2021-09-10 08:23 UTC, anuragpaliwal80 commented
As `DCO` check is not passing even after multiple tryouts, opened a new PR: https://github.com/chaos-mesh/chaos-mesh/pull/2292

2021-09-13 01:59 UTC, STRRL commented
> As `DCO` check is not passing even after multiple tryouts, opened a new PR: #2292

Got it! I am going to close this PR.

2021-09-13 01:59 UTC, closed without merging