[update] add awschaos api
chaos-mesh/chaos-mesh pull request #1656
Opened 2021-04-07 09:02 UTC by fewdan

Signed-off-by: “fewdan” <fewdan@hotmail.com>

### What problem does this PR solve?
add awschaos api

### What is changed and how does it work?
add awschaos api in dashboard (mainly experiments). 

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

2021-04-07 09:03 UTC, fewdan commented
@g1eny0ung Added the awschaos api, maybe the front end also needs to be modified.

2021-04-07 09:08 UTC, g1eny0ung commented
> @g1eny0ung Added the awschaos api, maybe the front end also needs to be modified.

I will review this PR ASAP and update the UI.

2021-04-08 04:22 UTC, g1eny0ung requested changes

2021-04-08 04:22 UTC, g1eny0ung commented on pkg/core/experiment.go
> +	Kind         string            `json:"kind" binding:"required,oneof=PodChaos NetworkChaos IoChaos KernelChaos TimeChaos StressChaos DNSChaos Awschaos"`
`Awschaos` => `AwsChaos`.

2021-04-09 09:43 UTC, g1eny0ung approved these changes
LGTM

2021-04-12 02:23 UTC, cwen0 approved these changes
LGTM

2021-04-12 02:24 UTC, cwen0 commented
/merge

2021-04-12 06:54 UTC, fewdan commented
/run-all-tests

2021-04-12 08:31 UTC, cwen0 commented
/run-e2e-tests

2021-04-12 08:52 UTC, cwen0 commented
/run-e2e-tests

2021-04-12 09:13 UTC, cwen0 commented
/run-e2e-tests

2021-04-12 09:31 UTC, merged