Kubernetes recommanded labels
chaos-mesh/chaos-mesh pull request #1735
Opened 2021-04-21 13:35 UTC by nlamirault

Next of #1538 1538

### What problem does this PR solve?

### What is changed and how does it work?

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

2021-04-22 02:24 UTC, STRRL requested changes
Thanks for your contribution! That's really hard work!

I noticed that the generated install.sh have extra 4 whitespace after the `label:`, I think we could fix that by using `nindent 4` instead of `indent 4`. And the `{{- define "chaos-mesh.labels" }}` in `_helpers.tpl` should be changed to `{{- define "chaos-mesh.labels" -}}`, with a suffix `-` to trim the whitespace/line-wrap.

And you might miss two place to use `{{ include template }}`, the one is the Service of chaos-dashboard at helm/chaos-mesh/templates/chaos-dashboard-deployment.yaml:88, the other one is ValidatingWebhookConfiguration at helm/chaos-mesh/templates/secrets-configuration.yaml:172

2021-04-23 23:44 UTC, STRRL commented
Hi @nlamirault, is this PR ready for review? 😁

2021-04-24 08:01 UTC, nlamirault commented
@STRRL yes

2021-04-25 09:58 UTC, STRRL commented
> And you might miss two place to use {{ include template }}, the one is the Service of chaos-dashboard at helm/chaos-mesh/templates/chaos-dashboard-deployment.yaml:88, the other one is ValidatingWebhookConfiguration at helm/chaos-mesh/templates/secrets-configuration.yaml:172

Hi @nlamirault, I think you might miss these two places, it could be instead with template "chaos-mesh.labels".

2021-04-25 10:05 UTC, STRRL requested changes
rest LGTM

2021-04-25 10:05 UTC, STRRL commented on helm/chaos-mesh/templates/_helpers.tpl
> +{{- end }}
I think we could make the same change like "chaos-mesh.labels" for preventing extra whitespace. :D

2021-04-25 11:10 UTC, nlamirault commented
I will fixe that asap

2021-04-26 02:14 UTC, STRRL approved these changes
LGTM

2021-04-26 02:15 UTC, STRRL commented
/run-e2e-tests

2021-04-27 05:26 UTC, cwen0 commented
/run-e2e-tests

2021-04-27 09:22 UTC, STRRL commented
Hi @nlamirault , I saw that the e2e test failed because it failed to install chaos-mesh by helm.

I think you should use `include "chaos-mesh.selectors" .` and `include "chaos-mesh.labels" .` with `nindent`, not `indent`, that will fix issue.

2021-04-27 09:23 UTC, STRRL commented
/lgtm cancel

2021-04-27 09:50 UTC, STRRL commented
/run-e2e-test

2021-04-28 05:33 UTC, cwen0 approved these changes
LGTM

2021-04-28 06:04 UTC, STRRL approved these changes
LGTM

2021-04-28 06:05 UTC, STRRL commented
/lgtm

2021-04-28 06:05 UTC, STRRL commented
/merge

2021-04-28 06:37 UTC, cwen0 commented
/run-e2e-tests

2021-04-28 10:18 UTC, cwen0 commented
/run-e2e-tests

2021-04-28 10:35 UTC, merged