used JoinHostPort wherever needed instead of Sprintf for network address
chaos-mesh/chaos-mesh pull request #1765
Opened 2021-05-04 07:46 UTC by nisarg1499

### What problem does this PR solve?

Fix SemGrep complaint to use JoinHostPort instead of Sprintf for network address construction.

```
opt.semgrep.sprintf-host-port
use net.JoinHostPort instead of fmt.Sprintf(c.GRPCPort, c.Host)
```
### What is changed and how does it work?
Replaced fmt.Sprintf with net.JoinHostPort, because fmt.Sprintf will cause issues in IPv6. Best practice is to use net.JoinHostPort
### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

2021-05-04 10:52 UTC, STRRL requested changes
Hi @nisarg1499, thanks for your contribution!

Here are something that needs to fix.

2021-05-04 10:52 UTC, STRRL commented on pkg/chaosdaemon/server.go
> +	return net.JoinHostPort(c.Host, fmt.Sprintf("%d", HTTPPort))
```suggestion
	return net.JoinHostPort(c.Host, fmt.Sprintf("%d", c.HTTPPort))
```

2021-05-04 10:52 UTC, STRRL commented on pkg/chaosdaemon/server.go
> +	return net.JoinHostPort(c.Host, fmt.Sprintf("%d", GRPCPort))
ditto

2021-05-04 10:53 UTC, STRRL commented
And do not forget to format the codes with `go fmt`, or execute `make check` directly. 😁

2021-05-04 10:55 UTC, nisarg1499 commented on pkg/chaosdaemon/server.go
> +	return net.JoinHostPort(c.Host, fmt.Sprintf("%d", HTTPPort))
Ohh. I'll fix this.

2021-05-04 10:55 UTC, nisarg1499 commented on pkg/chaosdaemon/server.go
> +	return net.JoinHostPort(c.Host, fmt.Sprintf("%d", GRPCPort))
Yaa this too.

2021-05-04 11:15 UTC, nisarg1499 commented on pkg/chaosdaemon/server.go
> +	return net.JoinHostPort(c.Host, fmt.Sprintf("%d", HTTPPort))
Change done @STRRL

2021-05-04 11:15 UTC, nisarg1499 commented on pkg/chaosdaemon/server.go
> +	return net.JoinHostPort(c.Host, fmt.Sprintf("%d", GRPCPort))
Change done @STRRL

2021-05-04 11:15 UTC, nisarg1499 commented
All change are done @STRRL 
Please review it.

2021-05-04 12:16 UTC, STRRL approved these changes
LGTM

2021-05-04 13:53 UTC, yeya24 approved these changes
LGTM

2021-05-04 13:54 UTC, yeya24 commented
/merge

2021-05-04 16:05 UTC, nisarg1499 commented
/retest

2021-05-04 17:30 UTC, nisarg1499 commented
@STRRL The jenkins job has succeeded. Then why Tide is showing not mergeable? How to check what's wrong in this case?

2021-05-05 09:22 UTC, STRRL commented
> @STRRL The jenkins job has succeeded. Then why Tide is showing not mergeable? How to check what's wrong in this case?

Thanks for your contribution! It requires maintainers to approve to run the CI for first-contribution of contributor, I just start it, and I think it will be merged very soon.

2021-05-05 19:33 UTC, nisarg1499 commented
@STRRL The e2e-test failed. I wanted to see the job logs in jenkins, but somehow I am not able to access Jenkins link. What should I do? Also any idea what could go wrong?

2021-05-06 02:37 UTC, YangKeao commented
/run-e2e-tests

2021-05-06 02:39 UTC, YangKeao commented
> @STRRL The e2e-test failed. I wanted to see the job logs in jenkins, but somehow I am not able to access Jenkins link. What should I do? Also any idea what could go wrong?

:facepalm: It seems to be an internal error. Now the CI cluster has resumed and we will try to merge this PR asap.

2021-05-06 02:47 UTC, YangKeao commented
/run-e2e-tests

2021-05-06 03:20 UTC, YangKeao commented
/merge

2021-05-06 05:31 UTC, YangKeao commented
/merge

2021-05-06 05:37 UTC, YangKeao commented
/merge

2021-05-06 06:51 UTC, YangKeao commented
/merge

2021-05-06 06:52 UTC, YangKeao commented
/merge

2021-05-06 07:14 UTC, merged