fixes static gocilint errors
chaos-mesh/chaos-mesh pull request #1780
Opened 2021-05-04 18:45 UTC by someshkoli

ignores if false positive and adds err checkk where require

Signed-off-by: someshkoli <kolisomesh27@gmail.com>

### What problem does this PR solve?

Fixes gocilint static errs. Ignores where irrelevant.
### What is changed and how does it work?

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

2021-05-05 09:47 UTC, STRRL commented
Oh, that's a big PR and we need more time for reviewing.

And what's the usage of comment `// nolint`? It seems it has no relation with muse-dev. Could you give us any documents or references?

2021-05-06 02:31 UTC, AsterNighT requested changes
FYI, your pr is fixing too many things and is conflict with almost every pr. You may have to fix lots of conflicts or break down your pr into several smaller ones..

2021-05-06 02:31 UTC, AsterNighT commented on controllers/networkchaos/partition/types.go
> +		e := t.Append(sourceSet)
pls use `err` instead of `e`

2021-05-06 02:31 UTC, AsterNighT commented on e2e-test/action.go
> +	er := e2eutil.WaitForCRDsEstablished(oa.apiExtCli, labels.Everything())
ditto

2021-05-06 02:31 UTC, AsterNighT commented on e2e-test/e2e/chaos/networkchaos/network_delay.go
> +	// nolint
I wonder what does this `// nolint` ignore? And what are the standards that you choose which error to fix and which to ignore?

2021-05-06 02:31 UTC, AsterNighT commented on pkg/chaosdaemon/client/utils.go
> +var _ = ctrl.Log.WithName("chaos-daemon-client-utils")
If it is unused, you can just delete this line.

2021-05-06 02:31 UTC, AsterNighT commented on pkg/chaosdaemon/ipset_server.go
> +		if err != nil {
This is intended. Pls revert this.

2021-05-06 02:31 UTC, AsterNighT commented on pkg/chaosdaemon/server.go
> +				return er
use `err` instead of `er`

2021-05-06 02:31 UTC, AsterNighT commented on pkg/grpc/utils.go
> +var _ = ctrl.Log.WithName("util")
ditto

2021-05-06 07:32 UTC, someshkoli commented
> FYI, your pr is fixing too many things and is conflict with almost every pr. You may have to fix lots of conflicts or break down your pr into several smaller ones..

I agree, I should probably use this as a ref PR and raise small PR's and lets do this one at a time, WDYT ?

2021-05-11 01:51 UTC, AsterNighT commented
> > FYI, your pr is fixing too many things and is conflict with almost every pr. You may have to fix lots of conflicts or break down your pr into several smaller ones..
> 
> I agree, I should probably use this as a ref PR and raise small PR's and lets do this one at a time, WDYT ?

Sry for the late reply. I suggest you check your fixes and pick out those which are already in master branch now first.

2021-05-28 01:37 UTC, STRRL commented
It seems this PR will not going to be merged anymore, I am going to close it.

Feel free to reopen.

2021-05-28 01:37 UTC, closed without merging