Migrate schedule fix
chaos-mesh/chaos-mesh pull request #1938
Opened 2021-06-04 06:46 UTC by AsterNighT

### What problem does this PR solve?

### What is changed and how does it work?

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

Related changes

- [ ] Need to update the documentation

### Does this PR introduce a user-facing change?

```release-note
NONE
```

2021-06-04 07:10 UTC, fewdan approved these changes
LGTM

2021-06-04 07:55 UTC, YangKeao commented
You have run this tools on examples? Cool :cool:

2021-06-04 07:56 UTC, YangKeao approved these changes
LGTM

2021-06-04 08:26 UTC, AsterNighT commented
Why?

2021-06-05 12:47 UTC, cwen0 commented
/run-e2e-tests

2021-06-07 03:53 UTC, YangKeao requested changes

2021-06-07 03:53 UTC, YangKeao commented on config/crd/bases/chaos-mesh.org_dnschaos.yaml
> +                  description: Map of string keys and values that can be used to select
Please don't wrap the YAML file 😢

2021-06-09 11:58 UTC, YangKeao commented
/run-e2e-tests

2021-06-10 02:25 UTC, AsterNighT commented
/run-e2e-tests

2021-06-10 07:10 UTC, YangKeao commented
/run-e2e-tests

2021-06-10 08:20 UTC, YangKeao commented
/merge

2021-06-10 08:50 UTC, YangKeao approved these changes
LGTM

2021-06-10 08:50 UTC, YangKeao commented
/merge

2021-06-10 08:51 UTC, YangKeao commented
@fewdan Your LGTM has been revoked.

2021-06-15 03:45 UTC, STRRL approved these changes
LGTM!

2021-06-15 03:46 UTC, STRRL commented
/merge

2021-06-15 04:20 UTC, merged