fix: add max validation to workers in stress chaos
chaos-mesh/chaos-mesh pull request #2010
Opened 2021-06-21 18:40 UTC by shivanshs9

### What problem does this PR solve?

Issue Number: close #1931

Problem Summary: stress-ng can launch at max 8192 workers, so StressChaos will fail silently in the case where workers is outside this range.

What's Changed:

Added a kubebuilder validation to force a maximum limit of 8192 for `spec.stressors.cpu.workers`.

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Breaking backward compatibility

### Release note 

```release-note
validation for number of cpu workers in stress chaos
```

2021-06-22 01:47 UTC, STRRL approved these changes

2021-06-22 01:48 UTC, STRRL requested changes
oh, you should execute `make generate yaml` to update the generated deepcopy code and CRD yaml files.

2021-06-22 08:03 UTC, WangXiangUSTC commented
LGTM

2021-06-22 08:03 UTC, WangXiangUSTC approved these changes

2021-06-23 02:20 UTC, STRRL approved these changes
LGTM!

2021-06-23 02:20 UTC, STRRL commented
/merge

2021-06-23 02:45 UTC, merged