gcp authentication integration
chaos-mesh/chaos-mesh pull request #2220
Opened 2021-08-13 03:02 UTC by YangKeao

### What problem does this PR solve?

Issue Number: close #2213

Problem Summary:

### What is changed and how it works?

What's Changed:

It provides three endpoints and adds a middleware:

```
GET /api/auth/gcp/redirect
```

It will redirect to the google login.

```
GET /api/auth/gcp/callback
```

It will exchange the oauth `access_token` and `refresh_token`. These token and the expiry will be included in the cookie. **notice:** the expiry will be URLEncoded (as in the cookie).

A middleware is added to the `gin` server, so that when the `x-authentication-method` is set to `gcp`, it will read token from the header and set the automatically refreshed token to the `Authentication` header.

2021-08-13 05:55 UTC, STRRL commented
please update the `install.sh`

2021-11-22 05:38 UTC, cwen0 reviewed
Rest LGTM

2021-11-22 06:20 UTC, YangKeao commented on pkg/dashboard/apiserver/auth/gcp/service.go
> +	log.Info("get oauth2Token", "oauth2Token", oauth2Token)
Nice catch!

2021-11-22 07:00 UTC, YangKeao commented on pkg/dashboard/apiserver/auth/gcp/service.go
> +	log.Info("get oauth2Token", "oauth2Token", oauth2Token)
Fixed.

2021-11-22 07:02 UTC, cwen0 approved these changes
LGTM

2021-11-22 08:54 UTC, g1eny0ung requested changes

2021-11-22 09:11 UTC, YangKeao commented on ui/package.json
> +    "js-cookie": "^3.0.0",
`/ui` folder has been reset to `upstream/master`.

2021-11-22 09:11 UTC, YangKeao commented on pkg/dashboard/apiserver/auth/gcp/middleware.go
> +		_ = c.Error(utils.ErrInternalServer.WrapWithNoMessage(err))
Fixed.

2021-11-22 09:11 UTC, YangKeao commented
@g1eny0ung PTAL

2021-11-22 11:37 UTC, g1eny0ung approved these changes
LGTM

2021-11-22 11:38 UTC, g1eny0ung commented
/merge

2021-11-23 02:03 UTC, cwen0 commented
/merge

2021-11-23 02:03 UTC, cwen0 approved these changes

2021-11-23 02:04 UTC, cwen0 commented
/merge

2021-11-23 02:43 UTC, merged