Change from DOCKER_REGISTRY to IMAGE_REGISTRY in some scripts
chaos-mesh/chaos-mesh pull request #2757
Opened 2022-01-07 07:36 UTC by YangKeao

### What problem does this PR solve?

In the previous PR of build scripts, I modified the `DOCKER_REGSITRY` environment variable to `IMAGE_REGISTRY` (to keep consistent with other variable like `IMAGE_PROJECT`, `IMAGE_TAG`...). In this PR, I will modify other scripts to fit this.

I will also modify other script inside the jenkins.

2022-01-10 09:08 UTC, STRRL reviewed
rest LGTM

2022-01-10 09:08 UTC, STRRL commented on hack/e2e.sh
> +    IMAGE_REGISTRY             image docker registry
```suggestion
    IMAGE_REGISTRY              image docker registry
```

2022-01-10 09:08 UTC, STRRL commented on hack/local-up-chaos-mesh.sh
> +    IMAGE_REGISTRY       image docker registry
```suggestion
    IMAGE_REGISTRY        image docker registry
```

2022-01-10 14:40 UTC, STRRL approved these changes

2022-01-10 14:41 UTC, STRRL commented
/merge

2022-01-11 09:34 UTC, YangKeao commented
/run-e2e-tests

2022-01-11 10:28 UTC, cwen0 approved these changes

2022-01-11 10:33 UTC, cwen0 commented
/merge

2022-01-11 11:31 UTC, Andrewmatilde requested changes
I think you should also replace `DOCKER_REGISTRY` with `IMAGE_REGISTRY` in doc. https://chaos-mesh.org/docs/production-installation-using-helm/

2022-01-11 13:27 UTC, merged

2022-01-13 12:56 UTC, STRRL commented
> I think you should also replace `DOCKER_REGISTRY` with `IMAGE_REGISTRY` in doc. [chaos-mesh.org/docs/production-installation-using-helm](https://chaos-mesh.org/docs/production-installation-using-helm/)

It seems this PR would not affect the helm chart.

2022-01-13 13:06 UTC, YangKeao commented
> > I think you should also replace `DOCKER_REGISTRY` with `IMAGE_REGISTRY` in doc. [chaos-mesh.org/docs/production-installation-using-helm](https://chaos-mesh.org/docs/production-installation-using-helm/)
> 
> It seems this PR would not affect the helm chart.

Yes. I should modify the development document https://chaos-mesh.org/docs/configure-development-environment/