Refine logging in pkg/bpm, move package level variable log into struct BackgroundProcessManager and ProcessBuilder as a field
chaos-mesh/chaos-mesh pull request #2909
Opened 2022-02-17 17:08 UTC by mikechengwei

### What problem does this PR solve?
#2870
### What's changed and how it works?

Use NewDefaultZapLogger.

### Related changes

- [ ] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [ ] release-2.1
  - [ ] release-2.0

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] No code
- [ ] Manual test (add steps below)

Side effects

- [ ] Breaking backward compatibility

### Release note 

```text
Please add a release note.

You can safely ignore this section if you don't think this PR needs a release note.
```

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

2022-02-18 05:30 UTC, STRRL requested changes

2022-02-18 05:30 UTC, STRRL commented on pkg/bpm/bpm.go
> +	log              logr.Logger
please use `logger` here.

2022-02-18 05:30 UTC, STRRL commented on pkg/bpm/bpm.go
> +	}
please do not create another logger, acquire the logger as a parameter in the constructor.

2022-02-18 05:30 UTC, STRRL commented on pkg/bpm/bpm.go
> +	}
ditto, please do not create another logger, acquire the logger as a parameter in the constructor.

2022-02-23 02:38 UTC, mikechengwei commented
@STRRL  I have reoptimize the code , plz help me review this pr again. Thks.

2022-02-28 07:07 UTC, STRRL reviewed
rest LGTM!

2022-02-28 07:07 UTC, STRRL commented on cmd/chaos-daemon/main.go
> +	ctrl.Log.WithName("chaos-daemon")
line 61 could be deleted

2022-02-28 07:07 UTC, STRRL commented on cmd/chaos-daemon/main.go
> +	server, err := chaosdaemon.BuildServer(conf, reg, rootLogger)
```suggestion
	server, err := chaosdaemon.BuildServer(conf, reg, rootLogger.WithName("chaos-daemon"))
```

2022-02-28 07:07 UTC, STRRL commented on pkg/chaosdaemon/server.go
> +	logger           logr.Logger
This logger seems not used at anywhere, we could remove it.

2022-03-01 15:47 UTC, closed without merging

2022-03-01 15:48 UTC, mikechengwei commented
This pr have finished.