refined logging
chaos-mesh/chaos-mesh pull request #3020
Opened 2022-03-14 15:57 UTC by basit9958

Signed-off-by: Basit Hasan <hasanbasit13@gmail.com>

### What problem does this PR solve?
> Closes: #2881

### What's changed and how it works?

### Related changes

- [x] Need to update `chaos-mesh/website`
- [ ] Need to update `Dashboard UI`
- Need to **cheery-pick to release branches**
  - [ ] release-2.1
  - [ ] release-2.0

### Checklist

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] No code
- [ ] Manual test (add steps below)

Side effects

- [ ] Breaking backward compatibility

### Release note 

```text
Please add a release note.

You can safely ignore this section if you don't think this PR needs a release note.
```

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

2022-03-14 16:02 UTC, basit9958 commented
cc @STRRL

2022-03-15 02:35 UTC, STRRL requested changes
Thanks for your contributrion!

PTAL!

2022-03-15 02:35 UTC, STRRL commented on pkg/dashboard/store/metrics/metrics.go
> +		log:             NewDefaultZapLogger(),
please do not instant new logger inside of the constructor, acquire it as one of constructor parameter.

2022-03-17 17:22 UTC, basit9958 commented
cc @STRRL  review please

2022-03-25 09:17 UTC, STRRL requested changes

2022-03-25 09:17 UTC, STRRL commented on pkg/dashboard/store/metrics/metrics.go
> +		log:             NewDefaultZapLogger(),
please use `log` in parameter instead of `NewDefaultZapLogger()`

2022-04-02 08:24 UTC, STRRL commented
Hi @basit9958, do you need some help? :)

2022-04-02 08:27 UTC, basit9958 commented
> Hi @basit9958, do you need some help? :)

I will resolve this by today 
😸

2022-04-03 04:13 UTC, basit9958 commented
cc @STRRL

2022-04-06 04:19 UTC, STRRL commented on pkg/dashboard/store/metrics/metrics.go
> +	log             logr.Logger
```suggestion
	Log             logr.Logger
```

It should use exported field with `fx` dependency injection.

rest LGTM! You are almost there.

2022-04-06 05:39 UTC, STRRL commented on pkg/dashboard/store/metrics/metrics.go
> +	log             logr.Logger
```suggestion
	Log             logr.Logger
```
It should use exported field with fx dependency injection.

rest LGTM! You are almost there.

2022-04-20 09:14 UTC, STRRL approved these changes
LGTM!

2022-04-20 10:42 UTC, iguoyr approved these changes
LGTM

2022-04-20 10:42 UTC, iguoyr commented
/merge

2022-04-21 05:22 UTC, merged