fix: ignore unnecessary workflows when **.md changes
chaos-mesh/chaos-mesh pull request #3721
Opened 2022-10-24 07:41 UTC by g1eny0ung

Signed-off-by: Yue Yang <g1enyy0ung@gmail.com>

### What problem does this PR solve?

### What's changed and how it works?

As the title.

### Related changes

- [ ] This change also requires further updates to the [website](https://github.com/chaos-mesh/website) (e.g. docs)
- [ ] This change also requires further updates to the `UI interface`
- Need to **cheery-pick to release branches**
  - [ ] release-2.4
  - [ ] release-2.3
  - [ ] release-2.2

### Checklist

CHANGELOG

- [ ] I have updated the `CHANGELOG.md`
- [x] I have labeled this PR with "no-need-update-changelog"

Tests

- [ ] Unit test
- [ ] E2E test
- [ ] No code
- [ ] Manual test (add steps below)

Side effects

- [ ] **Breaking backward compatibility**

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

2022-10-24 07:44 UTC, STRRL commented
I think we do not need to cherrypick into release-2.2 anymore.

2022-10-24 07:44 UTC, STRRL approved these changes
LGTM

2022-10-24 07:47 UTC, STRRL requested changes
Oops, I just realized that the Check "E2E Test Passed" is **required** for merging the PR..

2022-10-24 07:47 UTC, g1eny0ung commented
> I think we do not need to cherrypick into release-2.2 anymore.

Makes sense. 😌

2022-10-24 07:49 UTC, STRRL commented
> Oops, I just realized that the Check "E2E Test Passed" is **required** for merging the PR..

Maybe we should do the same thing like `ci.yaml` and `ci_skip.yaml`.

2022-10-24 07:51 UTC, g1eny0ung commented
> Oops, I just realized that the Check "E2E Test Passed" is **required** for merging the PR..

@STRRL We can use the same mechanism as `ci_skip.yaml`. I will update it soon.

2022-10-24 08:18 UTC, g1eny0ung commented on .github/workflows/integration_test_skip.yml
> +    runs-on: ${{ fromJson('{"amd64":"ubuntu-latest", "arm64":["self-hosted", "Linux", "ARM64"]}')[matrix.arch] }}
@STRRL If we just skip it, shall we just need to write `ubuntu-latest`?

2022-10-24 08:58 UTC, g1eny0ung commented on .github/workflows/integration_test_skip.yml
> +    runs-on: ${{ fromJson('{"amd64":"ubuntu-latest", "arm64":["self-hosted", "Linux", "ARM64"]}')[matrix.arch] }}
My mistake. An integration test is not required for merging PRs. I removed this file.

2022-10-25 06:46 UTC, g1eny0ung commented
> > Oops, I just realized that the Check "E2E Test Passed" is **required** for merging the PR..
> 
> @STRRL We can use the same mechanism as `ci_skip.yaml`. I will update it soon.

@STRRL After I tried and checked the Actions docs, I found that either `paths` or `dorny/paths-filter@v2` doesn't meet our need because we want **only markdown files to be changed** to not run the `E2E Test` workflow. Both of them will run if at least one other path matches.  :(

So I discover a new way to detect the changes. Using https://github.com/tj-actions/changed-files/ (support `only_changed` detection) and checking whether only markdown files changed. if it is, the rest of the logic is similar to `ci_skip.yml`.

2022-10-26 10:24 UTC, cwen0 approved these changes
LGTM

2022-10-26 10:26 UTC, cwen0 commented
/merge

2022-10-26 10:29 UTC, cwen0 commented
@STRRL PTAL

2022-10-31 02:12 UTC, merged