fix: resolve conflict from #3818
chaos-mesh/chaos-mesh pull request #3849
Opened 2022-12-09 03:12 UTC by STRRL

Signed-off-by: STRRL <im@strrl.dev>

### What problem does this PR solve?

#3818 merged with conflicts, this pr try to resolve these conflicts and push #3820 to get merged

### What's changed and how it works?

### Related changes

- [ ] This change also requires further updates to the [website](https://github.com/chaos-mesh/website) (e.g. docs)
- [ ] This change also requires further updates to the `UI interface`
- Need to **cheery-pick to release branches**
  - [ ] release-2.5
  - [ ] release-2.4

### Checklist

CHANGELOG

- [ ] I have updated the `CHANGELOG.md`
- [x] I have labeled this PR with "no-need-update-changelog"

Tests

- [ ] Unit test
- [ ] E2E test
- [x] No code
- [ ] Manual test (add steps below)

Side effects

- [ ] **Breaking backward compatibility**

### DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

2022-12-09 03:13 UTC, STRRL commented
/cc @g1eny0ung @cwen0 @FingerLeader

2022-12-09 08:59 UTC, g1eny0ung requested changes

2022-12-09 08:59 UTC, g1eny0ung commented on .github/workflows/upload_latest_files.yml
> -    runs-on: ubuntu-20.04
This `ubuntu-20.04` is not applied.

2022-12-10 01:40 UTC, STRRL commented on .github/workflows/upload_latest_files.yml
> -    runs-on: ubuntu-20.04
updated! PTAL :heart:

2022-12-12 17:24 UTC, g1eny0ung approved these changes

2022-12-12 17:28 UTC, merged