add extra sidecar container to dashboard in helm chart
chaos-mesh/chaos-mesh pull request #4164
Opened 2023-08-21 20:16 UTC by jamshidi799

## What problem does this PR solve?

## What's changed and how it works?

## Related changes

- [ ] This change also requires further updates to the [website](https://github.com/chaos-mesh/website) (e.g. docs)
- [ ] This change also requires further updates to the `UI interface`

## Cherry-pick to release branches (optional)

> This PR should be cherry-picked to the following release branches:

- [ ] release-2.6
- [ ] release-2.5

## Checklist

### CHANGELOG

> Must include at least one of them.

- [ ] I have updated the `CHANGELOG.md`
- [ x] I have labeled this PR with "no-need-update-changelog"

### Tests

> Must include at least one of them.

- [ ] Unit test
- [ ] E2E test
- [ x] Manual test

### Side effects

- [ ] **Breaking backward compatibility**

## DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

2023-08-22 14:31 UTC, cwen0 commented
@jamshidi799 Can you update the change logs?

2023-08-22 14:58 UTC, g1eny0ung requested changes

2023-08-22 14:58 UTC, g1eny0ung commented on helm/chaos-mesh/values.yaml
> +  # list of extra side car containers
```suggestion
  # List of extra sidecar containers
```

2023-08-23 03:48 UTC, g1eny0ung approved these changes
/lgtm

Thanks for your contribution! ❤️

2023-08-23 03:48 UTC, g1eny0ung commented
/cherrypick release-2.6

2023-08-23 04:57 UTC, merged

2023-08-23 07:15 UTC, jamshidi799 commented
> /lgtm
> 
> Thanks for your contribution! ❤️

Thank you too. I'm eager to do more.