add support of loadBalancerSourceRanges to chaos-dashboard service in…
chaos-mesh/chaos-mesh pull request #4172
Opened 2023-08-30 16:56 UTC by jamshidi799

## What problem does this PR solve?
This PR adds support of loadBalancerSourceRanges to chaos-dashboard service in the helm chart

 Close #3920 

## What's changed and how it works?

## Related changes

- [ ] This change also requires further updates to the [website](https://github.com/chaos-mesh/website) (e.g. docs)
- [ ] This change also requires further updates to the `UI interface`

## Cherry-pick to release branches (optional)

> This PR should be cherry-picked to the following release branches:

- [ ] release-2.6
- [ ] release-2.5

## Checklist

### CHANGELOG

> Must include at least one of them.

- [ ] I have updated the `CHANGELOG.md`
- [ ] I have labeled this PR with "no-need-update-changelog"

### Tests

> Must include at least one of them.

- [ ] Unit test
- [ ] E2E test
- [ ] Manual test

### Side effects

- [ ] **Breaking backward compatibility**

## DCO

If you find the DCO check fails, please run commands like below (Depends on the actual situations. For example, if the failed commit isn't the most recent) to fix it:

```shell
git commit --amend --signoff
git push --force
```

2024-02-02 09:10 UTC, g1eny0ung requested changes

2024-02-02 09:10 UTC, g1eny0ung commented on helm/chaos-mesh/templates/chaos-dashboard-deployment.yaml
>  {{- end }}
The below changes should be inserted before this `{{- end }}`.

2024-02-02 09:10 UTC, g1eny0ung commented on helm/chaos-mesh/templates/chaos-dashboard-deployment.yaml
> +{{- if and .Values.dashboard.service.type (eq .Values.dashboard.service.type "LoadBalancer") }}
```suggestion
{{- if and .Values.dashboard.service.type (eq .Values.dashboard.service.type "LoadBalancer") .Values.dashboard.service.loadBalancerSourceRanges }}
```

2024-02-02 10:57 UTC, jamshidi799 commented
now it should be ok

2024-02-02 22:27 UTC, g1eny0ung approved these changes
LGTM!

2024-02-04 09:22 UTC, jamshidi799 commented
thank you @g1eny0ung

2024-02-06 04:56 UTC, merged